<?php
/**
 * @file
 * Code for the OSHA Events feature.
 */

include_once 'osha_events.features.inc';

/**
 * Implements hook_form_alter().
 */

function osha_events_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'events_node_form') {

    $form['#validate'][] = 'osha_events_form_validate';

    // Activity field changes
    if (isset($form['field_activity'][LANGUAGE_NONE][0])) {
      unset($form['field_activity'][LANGUAGE_NONE]['add_more']);
      // Extract the field field tree to change cardinality
      $field = $form['field_activity'][LANGUAGE_NONE][0]['tid'];

      // Show the label as usual
      unset($field['#title_display']);

      // Field is not required, so add also an empty option.
      $field['#required'] = FALSE;
      $field['#options'] = array('' => t('- None -')) + $field['#options'];
      // Switch validator
      $field['#element_validate'] = array('options_field_widget_validate');

      $form['field_activity'][LANGUAGE_NONE] = $field;
    }
  }
}

/**
 * Implements hook_form_views_exposed_form_alter().
 */
function osha_events_form_views_exposed_form_alter(&$form, &$form_state) {
  // CW-1085 Default date now for start date in views filter.
  if ($form['#id'] == 'views-exposed-form-events-index-page') {
    $form['field_start_date_value']['#date_format'] = 'd/m/Y';
    $form['field_start_date_value2']['#date_format'] = 'd/m/Y';
    if (empty($form_state['input'])) {
      $date = new DateTime('now');
      $form_state['input']['field_start_date_value']['date'] = $date->format('d/m/Y');
      // Set the get value to prevent a bug in pager
      // See ticket CW-1438 and Drupal bug: www.drupal.org/node/1415306
      $_GET['field_start_date_value']['date'] = $date->format('d/m/Y');
    }
  }
}

/**
 * Validation callback.
 */
function osha_events_form_validate($form, &$form_state) {
  // When publishing an event, some fields are required.
  $values = $form_state['values'];
  $node = $form_state['node'];
  if ($values['status'] == 1) {
    if (empty($values['field_event_type'][LANGUAGE_NONE][0]['value']) || $values['field_event_type'][LANGUAGE_NONE][0]['value'] != t('Event')) {
      form_set_error('field_event_type', 'Only events of type <b>Event</b> may be published');
    }
    if (empty($values['body'][$node->language][0]['value'])) {
      form_set_error('body', 'You have to add a Description.');
    }
    if (empty($values['field_start_date'][LANGUAGE_NONE][0]['value'])) {
      form_set_error('field_start_date', 'You have to add a Start Date.');
    }
    if (empty($values['field_start_date'][LANGUAGE_NONE][0]['value2'])) {
      form_set_error('field_start_date', 'You have to add an End Date .');
    }
    if (empty($values['field_website_of_event'][LANGUAGE_NONE][0]['title'])) {
      form_set_error('field_website_of_event', 'You have to add a Web site name.');
    }
    if (empty($values['field_website_of_event'][LANGUAGE_NONE][0]['url'])) {
      form_set_error('field_website_of_event', 'You have to add a Web site url.');
    }
    if (empty($values['field_organization'][LANGUAGE_NONE][0]['value'])) {
      form_set_error('field_organization', 'You have to add an Organization.');
    }
    if (empty($values['field_country_code'][LANGUAGE_NONE][0]['value'])) {
      form_set_error('field_country_code', 'You have to add a Country Code.');
    }
    if (empty($values['field_city'][LANGUAGE_NONE][0]['value'])) {
      form_set_error('field_city', 'You have to add a City.');
    }
    if (empty($values['field_tags'][LANGUAGE_NONE][0]['tid'])) {
      form_set_error('field_tags', 'You have to add a Category.');
    }
    if ($values['field_for_the_web'][LANGUAGE_NONE][0]['value'] != 'Yes') {
      form_set_error('field_for_the_web', 'Event is not for web publishing. To override, set field "For the web" to "Yes".');
    }
  }
}


/**
 * Altering Date Popup to remove labels and description for specific field
 */
function osha_events_date_popup_process_alter(&$element, &$form_state, $context) {
  if ($element['#name'] == 'field_start_date_value' || $element['#name'] == 'field_start_date_value2') {
    //unset($element['date']['#description']);
    unset($element['date']['#title']);
  }
}

/**
 * Implements hook_osha_tmgmt_i18n_string_list().
 */
function osha_events_osha_tmgmt_i18n_string_list() {
  module_load_include('inc', 'osha_events', 'osha_events.translations');
  return osha_events_get_translatable_strings();
}


/**
 * Implements hook_user_role_insert().
 */
function osha_events_user_role_insert($role) {
  if ($role->name == 'Events Editor') {
    user_role_grant_permissions($role->rid, array(
      'access contextual links',
      'access dashboard',

      'create files',
      'view own private files',
      'view own files',
      'view files',

      'edit own image files',
      'edit any image files',
      'delete own image files',
      'download own image files',
      'download any image files',

      'use text format full_html',
      'use text format filtered_html',

      'access media browser',

      'edit meta tags',
      'access content',
      'view own unpublished content',
      'view revisions',

      'create events content',
      'edit own events content',
      'edit any events content',

      'create url aliases',
      'access administration pages',
      'view the administration theme',
    ));
  }
}

/**
 * Implements hook_phpexcel_export().
 */
function osha_events_phpexcel_export($op, &$data, &$phpexcel, $options, $column = NULL, $row = NULL) {
  $xls_colours = array(
    'Black' => '000000',
    'Red' => 'FF0000',
    'Grey' => '808080',
    'Yellow' => 'FFFF00',
    'Green' => '008000',
    'Blue' => '0000FF'
  );
  switch($op) {
    case 'post cell':
      if ($row == 1) {
        // first row
        $styleArray = array('font'  => array('bold' => TRUE));
        $phpexcel->getStyleByColumnAndRow($column,$row)->applyFromArray($styleArray);
      } else {
        // use the color named in the first cell of the current row
        $first_cell = $phpexcel->getCellByColumnAndRow(0, $row)->getValue();
        if (!empty($xls_colours[$first_cell])) {
          $styleArray = array(
            'font'  => array(
              'color' => array('rgb' => $xls_colours[$first_cell])
            )
          );
          $phpexcel->getStyleByColumnAndRow($column,$row)->applyFromArray($styleArray);
        }
      }
      break;
  }
}

/**
 * Implements hook_element_info_alter()
 */
function osha_events_element_info_alter(&$type) {
  if (isset($type['link_field'])) {
    $type['link_field']['#process'][] = 'osha_events_link_field_process';
  }
  if(isset($type['radios'])){
    $type['radios']['#process'][] = 'osha_events_radios_process';
  }
}

/**
 * Change field label
 */
function osha_events_link_field_process($element, $form_state, $complete_form) {
  switch ($element['#field_name']) {
    case 'field_website_of_event':
      $element['title']['#title'] = t('Website name');
      $element['url']['#title'] = t('Website url');
      break;
  }

  return $element;
}

/**
 * Unset N/A option
 */
function osha_events_radios_process($element, $form_state, $complete_form) {
  switch ($element['#field_name']) {
    case 'field_for_the_web':
      unset($element['#options']['_none']);
      unset($element['_none']);
      break;
  }

  return $element;
}
